name: "Publish"

on:
  push:
    branches: [ master ]

jobs:
  quality:
    name: Test Library
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npx jest --coverage

  publish:
    name: Publish Beta
    runs-on: ubuntu-latest
    needs: [quality]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci
      - run: npm run build
      - name: Setup Git Identity
        run: |
          git config user.name "Publish Bot"
          git config user.email github-actions@github.com
      - name: Increment beta version
        run: |
          npm version prerelease --preid=beta -m "Release: %s"
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
          npm publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Push new version to repo
        run: |
          git push
          git push --tags